version: 2
jobs:
    # The build job
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:6.10-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            # # Lint the source code
            # - run:
            #     name: Linting
            #     command: npm run lint
            # # Test the source code
            # - run:
            #     name: Testing
            #     command: npm run test
            # Build project with different configuration based on
            # the current branch
            - run:
                name: Building
                command: |
                    npm build -prod
            # Cache the dist folder for the deploy job
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist
            # Fix host authenticity
            - run:
                name: Fix host authenticity
                command: ssh-keyscan parkene.wpx.no >> ~/.ssh/known_hosts
            # deploy
            - run:
                name: Deploy
                command: scp -rp dist debian@parkene.wpx.no:apps/parks-frontend/